### ISSUE TITLE
Feedback from Atabak Alishiri

### ISSUE THREAD

**Issue by atabak-alishiri** [UBC-MDS/DSCI-532_2024_4_crime-tracker#51]
Dear Group 4,

I have reviewed your Vancouver Crime Tracker Dashboard, and I'm impressed with the comprehensive data and interactive elements you've incorporated. Below are some suggestions I believe could enhance your dashboard’s utility and user experience:

1. **Map Clarity:** Consider aggregating crime data points into clusters or a heat map to improve the map's readability and immediately identify high-crime areas.

2. **Marker Interactivity:** Enable tooltips or pop-up details for crime incidents on the map to provide context and data on user interaction.

3. **Visual Connection:** Reconfigure the layout to clearly associate "Total Crime Count" figures with the map data, potentially using matching colors or proximity placement.

4. **Layout Spacing:** Increase whitespace and consider collapsible sections for dense areas of the dashboard to enhance navigation and avoid user overwhelm.

5. **Map Legend Integration:** Add a clear legend for map colors corresponding to different crime types, facilitating user understanding of the map's color coding.

6. **Font Uniformity:** Unify font styles and sizes across the dashboard to create a cohesive visual flow and professional appearance.

7. **Dashboard Introduction:** Provide a brief introductory text or tutorial to guide new users on how to interact with the dashboard for an improved first-time experience.

I hope these suggestions serve as practical steps toward making your dashboard an even more potent analytical tool.

Best,
Atabak Alishiri

**Comment by WaleedMahmood1** [comment]
Thanks for the specific feedback @atabak-alishiri ! Below are a few comments regarding the feedback that you have provided:

- During the design phase of our dashboard, we discussed including the map plot as a heat map rather than with the data points. However, the discussion led to the fact that within each region there is still the dispersion of crime happening in specific streets, and this information would be lost with a heatmap. In our specific usage scenario, it is crucial for police patrolling to know which specific streets should be under higher priority and our current map plot serves this purpose.
- In addition, regarding the Dashboard introduction, we have included a section in our `README.md` that discusses how to navigate the dashboard. We hope this will allow users to better navigate the dashboard instead of having to self-learn it through trial and error.
- With regards to your remaining points, we have changed the layout and styling of our dashboard in order to make the dashboard less convoluted for our users so that they can follow a clear story of the various crimes in different neighborhoods and the frequency of these crimes at different times during the day.

Your feedback has been very influential in the improvement of our dashboard. Thanks again!
