### ISSUE TITLE
Feedback from Jordan Cairns

### ISSUE THREAD

**Issue by jcairn02** [UBC-MDS/DSCI-532_2024_4_crime-tracker#64]
Great job overall! I found myself exploring the ap for personal interest. A testament to the quality! I'm now scared to leave my apartment haha.

But we aren't reading this for the praise, we're here for the constructive feedback!

-A higher level criticism I'd want to address, is what if people wanted to use your tool for research purposes?
Is there a way to integrate the various widgets together in constructive ways to achieve this? Your usage scenario gives an example of "Adam may perhaps notice that there seems to be a greater count of "robberies/snatchings" being committed at "night" in "Hastings"". Addressing this query seems challenging with how the dashboard is laid out. I don't have a solution, but something to think about.

-The hourly count graph visually could benefit from some spicing up. It's at the center of the users focal point , large , yet the title is ambiguous and the color scheme is default. 

-It appears like there's a bug in the hourly count data? The hour zero count is so much higher than all the other values. Yes I could see midnight having the most crimes commited, but not anywhere close to the degree shown in the graph.

-Some way to show the relationship between area of the city and crime types could be interesting. For example what crimes are more likely to be commited in Kitsilano compared to downtown.  Only showing them on the street map doesn't really give a clear depiction of their relative relationships.

Was a pleasure reviewing your dashboard! Good interesting choice of data set and it was presented clearly.

**Comment by WaleedMahmood1** [comment]
Thanks for your feedback @jcairn02 ! A few comments regarding your feedback:

- Regarding the color of the line plot, if there is a single crime type selected, the color the line will correspond to the color of that specific crime in the first bar plot titled "Crime Count for Different Crimes". Once there are a greater number of crimes being selected, then we have the default color being applied to the line graph. If we choose to spice up the line plot by segregating the single line into multiple lines based on either crime type of neighborhood, we feel that it makes our bar plots redundant. The user still has the ability to look at specific crimes in specific regions and their counts at specific times during the day through the collective view of the plots in the dashboard.
- Regarding the high peak at midnight, it seems to be a bias in the data collection methodology. In our exploration of the raw data, we spotted that there were crimes reported without an actual exact time or were simply reported as midnight. This could have been due to the fact that sometimes, the victim is left stranded after a robbery and when they go to report the crime at their nearest police station, a couple of hours have passed, or even perhaps a day might have passed. In such a scenario, the police might have a uniform policy in place to report the time as midnight (i.e. the start of the day that the crime has been reported on).
- Concerning the point of comparison across two neighborhoods and the variation across the crime types for the two, a side-by-side boxplot has been discussed by the team to be a good fit. Given time limitations for this week, it has not been included as a task to improve our dashboard. However, it is definitely a potential avenue of functionality we plan to explore.
- Finally, regarding your first point on the integration of all the information in our dashboard, it seems a little bit challenging to integrate all of the information on `a greater count of "robberies/snatchings" being committed at "night" in "Hastings"` into a single plot. However, we have updated the layout of the plot so that this narrative can now be followed in a single view, rather than a plot. The user will begin from the left, selecting their respective neighborhood, to get the most prominent crimes occurring int heir neighborhood, moving to the left with the exact locations on the map plot of those crimes, along with the time of day that these crimes are most frequent.

Thanks for your feedback! It really pushed us to brainstorm and explore how to build a story with our dashboard.
