### ISSUE TITLE
Feedback from Wenyu Nie

### ISSUE THREAD

**Issue by wenyunie** [UBC-MDS/DSCI-532_2024_4_crime-tracker#67]
**Larger Points of Feedback**

- **Alignment with Usage Scenario and Target Audience**: The dashboard aligns well with the intended usage scenario for Chief Constable Adam Palmer and the Vancouver Police Department's requirements. It effectively visualizes crime data to assist in resource allocation and strategic planning. However, I would recommend adding an additional visualization that directly correlates crime type with time of day across neighborhoods. This could enable even quicker identification of patterns for certain types of crimes.

- **Intuitiveness and Usability**: The dashboard is user-friendly and provides a good amount of interaction through filters. However, it could be enhanced by integrating a tutorial or help overlay for first-time users. This would guide them through the features and ensure they leverage the tool to its fullest potential.

- **Plot Selection and Widget Interaction**: The selection of plots seems appropriate, but the hourly counts plot could include more detailed interaction. Consider integrating a feature that allows users to click on a specific hour to drill down into more granular data, such as the types of crimes occurring during that hour.

- **Plot Descriptions and Intuitiveness**: The plots are generally self-explanatory, but including a brief description or legend for each plot could enhance clarity, especially for less tech-savvy users.

**Smaller Points of Feedback**

- **Readability of Text**: Some text elements, particularly in the bar chart, are difficult to read due to small font size. Increasing the text size or the angle or changing the font could improve readability.
- **Dashboard Layout**: The layout is clean and follows a logical structure, but it might benefit from a slight rearrangement. Placing the temporal distribution plot next to the spatial heatmap could help users make connections between time and location more efficiently.
- **Widget Functionality**: Ensure that the filtering options include a clear way to reset to default or when all filters are removed. This can prevent confusion and enhance the user's ability to start a new analysis quickly.

**Suggestions**

Your dashboard provides a solid foundation for the Vancouver Police Department to analyze crime data. To further improve it, I recommend focusing on a few areas:
* Enhanced Plot Interaction: Allow for more detailed interaction with plots for deeper analysis. e.g. selecting points in the map, zooming in to certain time points of the time plot.
* User Onboarding: Implement a help feature for new users to get accustomed to the dashboard quickly.
* Text Readability: Improve the readability of text on all visualizations.
* Dashboard Layout Optimization: Reassess the layout to facilitate a better data analysis flow.

Your work so far is already very wonderful and the topic is very interesting. I believe with a few adjustments, it can become an even more powerful tool for the Vancouver Police Department. I look forward to seeing the implemented changes and am confident they will greatly enhance the utility and user experience of the "Crime Tracker" dashboard. Thank you for deliverying such a cool dashboard!

**Comment by WaleedMahmood1** [comment]
Thanks for the great feedback @wenyunie ! Below are a few comments about your feedback on things that we incorporated into our dashboard, and aspects that we might explore at a later stage perhaps:

- Your first point about including a visualization that correlates crime type with time of day across neighborhoods is something that our team discussed initially; however, we believe that the current bar plots allow the Vancouver Police Department (VPD) to determine which crimes are highest in which neighborhoods, and then they can correspond this information with time of day occurrences of these crimes through the use of the dropdowns.
- Your feedback about the integration of a tutorial is excellent. Currently, we felt that due to the constraints of time with our studies and work, we included a gif in our `README.md` to provide a simple glance at how our dashboard will function. However, it is definitely essential to include a walkthrough video guiding our target audience of the usage of our dashboard.

Overall feedback points:
We have worked on refurbishing the layout of our dashboard to allow for a smoother understanding of all of the information, that is less convoluted for the user. And also worked on the color and fonts to improve readability so that there is a smoother flow from viewing data to interpreting it.

Thanks for your feedback!
