### ISSUE TITLE
Feedback from Hina Bandukwala

### ISSUE THREAD

**Issue by hbandukw** [UBC-MDS/DSCI-532_2024_4_crime-tracker#68]
Firstly, great job on the dashboard. It was truly hard for me to come up with suggestions, so awesome work!

- [x] Minor suggestions for improving the statistics card: Maybe adding a light colour to the card to differentiate it from the widgets would be nice for the overall layout. 
- [x] Same thing for figure titles: They are getting lost on the page, so maybe bolding them would be helpful?
- [ ] It would be helpful to know how the crime categories are defined e.g. "Mischief" is ambiguous. Also, I don't think you mentioned where the data is from. You could include these details in the README or with a "Learn more" button as Joel suggested. 
- [ ] For the overall "Total Crime Count", is that a total for Vancouver? It could be helpful to see percentage changes in crime rate from the previous year displayed on the card.  
- [ ] In the bar plot that displays the breakdown of crime types, including a percentage in the tooltip would be helpful. For example, for "Theft Vehicle", it would indicate both the count and what percentage of the total crime does it account for. Same for the crime count per neighbourhood. 
- [x] The static plots (i.e. barplot and card) could be placed together and differentiated from the other three plots which change based on user input. 
- [ ] I  like the idea of the "hourly count". It would be useful to have a static time plot that shows hourly crime counts for the entire city, broken up by the type of crime. For example, if law enforcement decides to allocate resources to Kitsilano, they could use this plot the following way: Given that vehicle theft is high between 1 AM to 3 AM in Kitsilano, we can allocate X resources here. 

Overall, great job everyone!!

**Comment by WaleedMahmood1** [comment]
Thanks for your highly fine-tuned feedback @hbandukw ! A few comments about the feedback we have chosen not to push into the working of our dashboard:

- Regarding the crime categories, the original names of the crimes were far more confusing, and we simplified and updated them in order for less confusion in the crime types. We believe that for a user that wishes to acquire an even more expert understanding of the crimes, the inclusion of the reference of where we got our data from is sufficient for a curious user to explore.
- Regarding looking at the comparison of crimes from previous years, that would serve a different purpose for policymakers. Currently, the situation is that there are certain crimes that are high in occurrence is certain neighborhoods. And to address this, the Vancouver Police Department (VPD) will need to allocate resources to tackle these crimes. Once these policies and plans have been implemented, VPD can look into the effectiveness of their allocation next year and go  into switching their plans up. So the functionality of the inclusion of comparison across years is a n aspect that will be implemented in our dashboard at a later stage, so that we are not overloading the user with too much information that might convolute their policy-making.
- Regarding having one "static time plot that shows hourly crime counts for the entire city, broken up by the type of crime", our dashboard currently covers this functionality through the bar plots and the line plot, where the user can actively select the regions they wish to explore, from the dropdown, and they will obtain the precise information you have recommended. So the inclusion of the static time plot would be a bit redundant.

Thanks again! The rest of your feedback has been incorporated in the latest version of our dashboard!
